### ISSUE TITLE
Data Download

### ISSUE THREAD

**Issue by akasom89** [ngoldman/himawari-urls#4]
Hello @ungoldman,

Thank you for sharing the code.

I encountered an issue regarding AHI data. Currently, I am using the AWS public bucket to download Himawari-9 data. However, I've noticed that the data latency is higher compared to ABI data(GOES). It may take up to 8 minutes to access the acquired full disk image, which normally takes about 1 minute for ABI (GOES).

I'm wondering if there are any solutions or alternatives for accessing Himawari data in a more real-time manner.

Regards

**Comment by ungoldman** [comment]
Hi @akasom89

I have no idea, I haven't been active in this space for several years. Good luck!
